version: '3.8'

services:
  db:
    image: 'postgres'
    container_name: monitoring-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitoring
    ports:
      - '5434:5432'
    networks:
      - monitoring
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

  nestjs-app:
    build: .
    ports:
      - '5666:5666'
    restart: unless-stopped 
    depends_on: 
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.8.0
    ports:
      - '3100:3100'
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    restart: unless-stopped 
    networks:
      - monitoring
    volumes:
      - loki-data:/loki

  grafana:
    image: grafana/grafana:9.5.3
    ports:
      - '3020:3000'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped 
    depends_on: 
      - loki
      #- prometheus
    networks:
      - monitoring

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped 
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  postgresql-volume:
  grafana-data:
  loki-data:
  rabbitmq-data: